In [1]:
import json
import random
import pandas as pd
from pathlib import Path

In [2]:
domains = {
    "software": [
        "Python Developer",
        "Backend Engineer",
        "Machine Learning Engineer",
        "Full Stack Developer",
        "Data Scientist"
    ],
    "marketing": [
        "Digital Marketing Specialist",
        "SEO Analyst",
        "Content Strategist",
        "Social Media Manager"
    ],
    "finance": [
        "Financial Analyst",
        "Investment Analyst",
        "Accountant",
        "Risk Analyst"
    ],
    "hr": [
        "HR Manager",
        "Talent Acquisition Specialist",
        "HR Generalist"
    ]
}

skills = {
    "software": [
        "Python", "TensorFlow", "Django", "Flask", "Docker", "SQL",
        "Machine Learning", "REST APIs", "Git"
    ],
    "marketing": [
        "SEO", "Google Analytics", "Content Marketing",
        "Social Media Marketing", "Email Marketing"
    ],
    "finance": [
        "Financial Modeling", "Excel", "Risk Analysis",
        "Budget Forecasting", "Investment Analysis"
    ],
    "hr": [
        "Recruitment", "Employee Relations", "HR Policies",
        "Talent Management"
    ]
}

companies = [
    "Google", "Microsoft", "Amazon", "Infosys",
    "TCS", "Accenture", "Meta", "IBM"
]

names = [
    "Rahul Sharma", "Amit Verma", "Priya Singh",
    "Anjali Gupta", "Rohit Kumar", "Sneha Patel",
    "Vikas Mehta", "Neha Kapoor"
]

def generate_profile():
    domain = random.choice(list(domains.keys()))
    position = random.choice(domains[domain])
    skillset = random.sample(skills[domain], k=3)
    company = random.choice(companies)
    years = random.randint(1, 10)

    return {
        "name": random.choice(names),
        "domain": domain,
        "position": position,
        "skills": ", ".join(skillset),
        "company": company,
        "years_experience": years
    }

In [3]:
profiles = []

for _ in range(600):
    profiles.append(generate_profile())

df = pd.DataFrame(profiles)

output_path = Path("../data/raw/synthetic_profiles.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)

df.to_csv(output_path, index=False)

print("Dataset generated:", output_path)
print(df.head())

Dataset generated: ..\data\raw\synthetic_profiles.csv
           name     domain                       position  \
0  Rahul Sharma  marketing           Social Media Manager
1   Rohit Kumar    finance             Investment Analyst
2  Anjali Gupta         hr                     HR Manager
3  Rahul Sharma   software               Backend Engineer
4   Vikas Mehta         hr  Talent Acquisition Specialist

                                              skills    company  \
0           SEO, Content Marketing, Google Analytics       Meta
1           Financial Modeling, Excel, Risk Analysis       Meta
2  HR Policies, Employee Relations, Talent Manage...  Accenture
3                              Django, Python, Flask       Meta
4        Talent Management, Recruitment, HR Policies    Infosys

   years_experience
0                 2
1                 4
2                10
3                 2
4                 2

In [6]:
from pathlib import Path
import json
import pandas as pd
import random

# Paths
templates_path = Path("../rubrics/summary_templates.json")
profiles_path = Path("../data/raw/synthetic_profiles.csv")

# Load templates
with open(templates_path, "r") as f:
    templates_data = json.load(f)

templates = templates_data["templates"]

# Load profiles
df = pd.read_csv(profiles_path)

print("Templates:", len(templates))
print("Profiles:", len(df))

Templates: 50
Profiles: 600

In [7]:
print("Templates:", len(templates))
print("Profiles:", len(df))

Templates: 50
Profiles: 600

In [8]:
def build_profile_text(row):
    return (
        f"{row['name']} is a {row['position']} with "
        f"{row['years_experience']} years of experience at {row['company']}. "
        f"Skills include {row['skills']}."
    )

df["profile_text"] = df.apply(build_profile_text, axis=1)

df[["profile_text"]].head()

                                        profile_text
0  Rahul Sharma is a Social Media Manager with 2 ...
1  Rohit Kumar is a Investment Analyst with 4 yea...
2  Anjali Gupta is a HR Manager with 10 years of ...
3  Rahul Sharma is a Backend Engineer with 2 year...
4  Vikas Mehta is a Talent Acquisition Specialist...

In [9]:
import random

num_templates = len(templates)

df["template_index"] = [
    random.randint(0, num_templates - 1)
    for _ in range(len(df))
]

df[["profile_text", "template_index"]].head()

                                        profile_text  template_index
0  Rahul Sharma is a Social Media Manager with 2 ...              11
1  Rohit Kumar is a Investment Analyst with 4 yea...              26
2  Anjali Gupta is a HR Manager with 10 years of ...              44
3  Rahul Sharma is a Backend Engineer with 2 year...              30
4  Vikas Mehta is a Talent Acquisition Specialist...              39

In [10]:
output_path = Path("../data/labeled/weak_labels.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)

df[["profile_text", "template_index"]].to_csv(output_path, index=False)

print("Weak labels saved:", output_path)

Weak labels saved: ..\data\labeled\weak_labels.csv